name: Build all Typst documents

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # 1. Trouver tous les fichiers .typ
  find-files:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.prepare.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: prepare
        shell: bash
        run: |
          echo "🔍 Searching for .typ files (excluding ./config.typ)..."
          mapfile -d '' -t files < <(find . -type f -name '*.typ' ! -path './config.typ' -print0)

          if [ ${#files[@]} -eq 0 ]; then
            echo "❌ No Typst files found. Exiting."
            exit 1
          fi

          printf '%s\n' "${files[@]}"
          printf '%s\n' "${files[@]}" | python3 -c 'import sys, json; print(json.dumps([l.rstrip() for l in sys.stdin]))' > matrix.json
          echo "matrix=$(cat matrix.json)" >> $GITHUB_OUTPUT

  # 2. Compiler chaque fichier .typ en PDF
  build:
    needs: find-files
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJson(needs.find-files.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Typst document
        run: |
          base=$(basename "${{ matrix.file }}" .typ)
          mkdir -p build
          typst compile "${{ matrix.file }}"
          # déplacer le PDF généré dans le dossier build avec nom propre
          mv "${{ matrix.file%.typ }}.pdf" "build/${base}.pdf"

      - name: Upload individual PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.file }}
          path: build/${{ matrix.file%.typ }}.pdf

  # 3. Collecter tous les PDFs dans un artefact global
  collect:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all individual PDFs
        uses: actions/download-artifact@v4
        with:
          path: build

      - name: Set artifact name with timestamp
        id: artifact_name
        run: |
          TIMESTAMP=$(date +%Y-%m-%d-%H%M%S)
          ARTIFACT_NAME="PDFs_${TIMESTAMP}"
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV
          echo "Artifact will be named: $ARTIFACT_NAME.zip"

      - name: Upload final PDFs bundle
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: build/*.pdf

      - name: Create Release (if pushing a tag)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          name: "Cours — ${{ github.ref_name }}"
          files: build/*.pdf
