name: Build and Publish Typst PDFs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build Typst documents
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.artifact.outputs.ARTIFACT_NAME }}
    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Installer Typst
      - name: Install Typst
        run: |
          curl -L https://github.com/typst/typst/releases/latest/download/typst-x86_64-unknown-linux-musl.tar.xz \
            -o typst.tar.xz
          tar -xJf typst.tar.xz
          sudo mv typst-x86_64-unknown-linux-musl/typst /usr/local/bin/
          typst --version

      # 3. Créer un timestamp unique pour tout le job
      - name: Set timestamp
        id: timestamp
        run: |
          TIMESTAMP=$(date +%Y-%m-%d-%H%M%S)
          echo "TIMESTAMP=$TIMESTAMP" >> $GITHUB_ENV

      # 4. Trouver tous les fichiers .typ
      - name: Find Typst files
        id: find
        shell: bash
        run: |
          echo "🔍 Searching for .typ files..."
          mapfile -d '' -t files < <(find . -type f -name '*.typ' ! -path './config.typ' -print0)
          if [ ${#files[@]} -eq 0 ]; then
            echo "❌ No Typst files found. Exiting."
            exit 1
          fi
          printf '%s\n' "${files[@]}" > typst_files.txt
          echo "Found ${#files[@]} files:"
          cat typst_files.txt

      # 5. Compiler tous les fichiers en PDFs avec le timestamp global
      - name: Compile Typst files
        shell: bash
        run: |
          mkdir -p release
          while read -r typfile; do
            base=$(basename "$typfile" .typ)
            outfile="release/${base}_${TIMESTAMP}.pdf"
            echo "🔧 Compiling $typfile → $outfile"
            typst compile "$typfile" "$outfile" --root .
          done < typst_files.txt

      # 6. Upload bundle final des PDFs comme artifact GitHub Actions
      - name: Set artifact name
        id: artifact
        run: |
          ARTIFACT_NAME="PDFs_${TIMESTAMP}"
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_OUTPUT
          echo "Artifact will be named: $ARTIFACT_NAME.zip"

      - name: Upload PDFs artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.artifact.outputs.ARTIFACT_NAME }}
          path: release/*.pdf

      # 7. Créer index.html avec le timestamp global
      - name: Generate index.html for GitHub Pages
        shell: bash
        run: |
          cd release
          echo "<!DOCTYPE html><html><head><meta charset='UTF-8'><title>PDFs</title></head><body><h1>Télécom Physique Strasbourg — Informatique et Réseaux — Promotion 2028</h1><h2>Cours</h2><ul>" > index.html
          for pdf in *.pdf; do
            echo "<li><a href=\"$pdf\">$pdf</a></li>" >> index.html
          done
          echo "</ul></body></html>" >> index.html
          cd ..

      # 8. Upload PDFs + index.html pour GitHub Pages
      - name: Upload PDFs for GitHub Pages
        id: deployment
        uses: actions/upload-pages-artifact@v4
        with:
          path: release

  deploy:
    name: Deploy PDFs to GitHub Pages
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
